#!/bin/bash

CERT_HOME=/opt/Certification/scripts
BACKUP_HOME=${CERT_HOME}/bak
SIM_TST=sim
SCAN_TST=scan_cell

SHORT_test="Short Test: SIM detect only"
FULL_test="Full Test: SIM detect + Network Scan"



function set_cell_test_SIM() {
	mv ${CERT_HOME}/${SCAN_TST} ${BACKUP_HOME} &> /dev/null
	mv ${BACKUP_HOME}/${SIM_TST} ${CERT_HOME} &> /dev/null
}

function set_cell_test_SCAN() {
	mv ${CERT_HOME}/${SIM_TST} ${BACKUP_HOME} &> /dev/null
	mv ${BACKUP_HOME}/${SCAN_TST} ${CERT_HOME} &> /dev/null
}

function cell_test_cfg() {
	PS3="Select Action: "
	select t in "${SHORT_test}" "${FULL_test}"; do
		case ${t} in
		'')
			echo Select a correct Action from the list >&2
			continue
			;;
		"${SHORT_test}")
			set_cell_test_SIM
			break
			;;
		"${FULL_test}")
			set_cell_test_SCAN
			break
			;;
		esac
	done
}

cell_test_cfg
