#!/bin/bash

CERT_HOME=/opt/Certification/scripts
CERT_INCLUDE_DIR=${CERT_HOME}/cert
. ${CERT_INCLUDE_DIR}/config.inc

declare -a STATUS=("FAIL" "OK")

i=1
for t in $(ls ${CERT_TEST_STATUS_HOME}) ; do
	test_name=${t%"_test.run"}
	test_stat=$(cat ${CERT_TEST_STATUS_HOME}/${t})
	printf "%d) %-12s: %s\n" $((i++)) "${test_name}" "${STATUS[${test_stat}]}"
done
